let paisesUsinas = [{'pais': 'Argentina',
  'descricao': 'Argentina é uma nação que possui 4 reatores nucleares, localizados em 2 cidades. Os reatores são dos tipos PHWR e PWR, sendo que, 3 em situação Operacional e 1 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=AR',
  'tags': 'Argentina, AR, ARG'},
 {'pais': 'Armênia',
  'descricao': 'Armênia é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 1 Desativado Permanentemente e 1 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=AM',
  'tags': 'Armênia, Armenia, AM, ARM'},
 {'pais': 'Bangladesh',
  'descricao': 'Bangladesh é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 2 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=BD',
  'tags': 'Bangladesh, BD, BGD'},
 {'pais': 'Bielorrússia',
  'descricao': 'Bielorrússia é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 2 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=BY',
  'tags': 'Bielorrússia, Bielorrussia, Belarus, BY, BYE'},
 {'pais': 'Bélgica',
  'descricao': 'Bélgica é uma nação que possui 8 reatores nucleares, localizados em 3 cidades. Os reatores são do tipo PWR, sendo que, 3 Desativados Permanentemente e 5 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=BE',
  'tags': 'Bélgica, Belgica, BE, BEL'},
 {'pais': 'Brasil',
  'descricao': 'Brasil é uma nação que possui 3 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 2 em situação Operacional e 1 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=BR',
  'tags': 'Brasil, BR, BRA'},
 {'pais': 'Bulgária',
  'descricao': 'Bulgária é uma nação que possui 6 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 4 Desativados Permanentemente e 2 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=BG',
  'tags': 'Bulgária, Bulgaria, BG, BUL'},
 {'pais': 'Canadá',
  'descricao': 'Canadá é uma nação que possui 25 reatores nucleares, localizados em 6 cidades. Os reatores são dos tipos PHWR e HWLWR, sendo que, 19 em situação Operacional e 6 Desativados Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=CA',
  'tags': 'Canadá, Canada, CA, CAN'},
 {'pais': 'China',
  'descricao': 'China é uma nação que possui 84 reatores nucleares, localizados em 21 cidades. Os reatores são dos tipos PWR, FBR, PHWR e HTGR, sendo que, 28 Em Contrução e 56 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=CN',
  'tags': 'China, CN, CPR'},
 {'pais': 'Republica Tcheca',
  'descricao': 'Republica Tcheca é uma nação que possui 6 reatores nucleares, localizados em 2 cidades. Os reatores são do tipo PWR, sendo que, 6 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=CZ',
  'tags': 'Republica Tcheca, Tchequia, Tchéquia, CZ, CEH'},
 {'pais': 'Egito',
  'descricao': 'Egito é uma nação que possui 4 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 4 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=EG',
  'tags': 'Egito, EG, EGY'},
 {'pais': 'Finlândia',
  'descricao': 'Finlândia é uma nação que possui 5 reatores nucleares, localizados em 2 cidades. Os reatores são dos tipos PWR e BWR, sendo que, 5 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=FI',
  'tags': 'Finlândia, Finlandia, FI, FIN'},
 {'pais': 'França',
  'descricao': 'França é uma nação que possui 71 reatores nucleares, localizados em 22 cidades. Os reatores são dos tipos PWR, GCR, FBR e HWGCR, sendo que, 56 em situação Operacional, 14 Desativados Permanentemente e 1 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=FR',
  'tags': 'França, Franca, FR, FRA'},
 {'pais': 'Alemanha',
  'descricao': 'Alemanha é uma nação que possui 36 reatores nucleares, localizados em 25 cidades. Os reatores são dos tipos HTGR, PWR, BWR, FBR, PHWR e HWGCR, sendo que, 33 Desativados Permanentemente e 3 com o Descomissionamento Concluído.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=DE',
  'tags': 'Alemanha, DE, GER'},
 {'pais': 'Hungria',
  'descricao': 'Hungria é uma nação que possui 4 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 4 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=HU',
  'tags': 'Hungria, HU, HUN'},
 {'pais': 'Índia',
  'descricao': 'Índia é uma nação que possui 31 reatores nucleares, localizados em 7 cidades. Os reatores são dos tipos PHWR, PWR, FBR e BWR, sendo que, 20 em situação Operacional, 7 Em Contrução e 4 com a Operação Supensa.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=IN',
  'tags': 'Índia, India, IN, IND'},
 {'pais': 'Irã',
  'descricao': 'Irã é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 1 em situação Operacional e 1 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=IR',
  'tags': 'Irã, Ira, IR, IRA'},
 {'pais': 'Itália',
  'descricao': 'Itália é uma nação que possui 4 reatores nucleares, localizados em 4 cidades. Os reatores são dos tipos BWR, PWR e GCR, sendo que, 4 Desativados Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=IT',
  'tags': 'Itália, Italia, IT, ITA'},
 {'pais': 'Japão',
  'descricao': 'Japão é uma nação que possui 62 reatores nucleares, localizados em 20 cidades. Os reatores são dos tipos HWLWR, BWR, PWR, FBR e GCR, sendo que, 27 Desativados Permanentemente, 12 em situação Operacional, 21 com a Operação Supensa e 2 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=JP',
  'tags': 'Japão, Japao, JP, JPN'},
 {'pais': 'Cazaquistão',
  'descricao': 'Cazaquistão é uma nação que possui 1 reator nuclear, localizado em 1 cidade. O reator é do tipo FBR, sendo que, 1 Desativado Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=KZ',
  'tags': 'Cazaquistão, Cazaquistao, Kazaquistão, Kazaquistao, KZ, KAZ'},
 {'pais': 'Coreia do Sul',
  'descricao': 'Coreia do Sul é uma nação que possui 30 reatores nucleares, localizados em 6 cidades. Os reatores são dos tipos PWR e PHWR, sendo que, 26 em situação Operacional, 2 Desativados Permanentemente e 2 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=KR',
  'tags': 'Coreia do Sul, KR, ROK'},
 {'pais': 'Lituânia',
  'descricao': 'Lituânia é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo LWGR, sendo que, 2 Desativados Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=LT',
  'tags': 'Lituânia, Lituania, LT, LIT'},
 {'pais': 'México',
  'descricao': 'México é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo BWR, sendo que, 2 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=MX',
  'tags': 'México, Mexico, MX, MEX'},
 {'pais': 'Holanda',
  'descricao': 'Holanda é uma nação que possui 2 reatores nucleares, localizados em 2 cidades. Os reatores são dos tipos PWR e BWR, sendo que, 1 em situação Operacional e 1 Desativado Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=NL',
  'tags': 'Holanda, Paises Baixos, NL, NET'},
 {'pais': 'Paquistão',
  'descricao': 'Paquistão é uma nação que possui 7 reatores nucleares, localizados em 2 cidades. Os reatores são dos tipos PWR e PHWR, sendo que, 6 em situação Operacional e 1 Desativado Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=PK',
  'tags': 'Paquistão, Paquistao, PK, PAK'},
 {'pais': 'Romênia',
  'descricao': 'Romênia é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PHWR, sendo que, 2 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=RO',
  'tags': 'Romênia, Romenia, RO, ROM'},
 {'pais': 'Rússia',
  'descricao': 'Rússia é uma nação que possui 51 reatores nucleares, localizados em 13 cidades. Os reatores são dos tipos LWGR, PWR e FBR, sendo que, 11 Desativados Permanentemente, 36 em situação Operacional e 4 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=RU',
  'tags': 'Rússia, Russia, RU, RUS'},
 {'pais': 'Eslováquia',
  'descricao': 'Eslováquia é uma nação que possui 9 reatores nucleares, localizados em 3 cidades. Os reatores são dos tipos HWGCR e PWR, sendo que, 3 Desativados Permanentemente, 5 em situação Operacional e 1 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=SK',
  'tags': 'Eslováquia, Eslovaquia, SK, SLO'},
 {'pais': 'Eslovênia',
  'descricao': 'Eslovênia é uma nação que possui 1 reator nuclear, localizado em 1 cidade. O reator é do tipo PWR, sendo que, 1 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=SI',
  'tags': 'Eslovênia, Eslovenia, SI, SVN'},
 {'pais': 'África do Sul',
  'descricao': 'África do Sul é uma nação que possui 2 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 2 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=ZA',
  'tags': 'África do Sul, Africa do Sul, ZA, SAF'},
 {'pais': 'Espanha',
  'descricao': 'Espanha é uma nação que possui 10 reatores nucleares, localizados em 7 cidades. Os reatores são dos tipos PWR, BWR e GCR, sendo que, 7 em situação Operacional e 3 Desativados Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=ES',
  'tags': 'Espanha, ES, SPA'},
 {'pais': 'Suécia',
  'descricao': 'Suécia é uma nação que possui 13 reatores nucleares, localizados em 5 cidades. Os reatores são dos tipos PHWR, BWR e PWR, sendo que, 7 Desativados Permanentemente e 6 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=SE',
  'tags': 'Suécia, Suecia, SE, SWE'},
 {'pais': 'Suíça',
  'descricao': 'Suíça é uma nação que possui 6 reatores nucleares, localizados em 5 cidades. Os reatores são dos tipos PWR, BWR e HWGCR, sendo que, 4 em situação Operacional e 2 Desativados Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=CH',
  'tags': 'Suíça, Suiça, Suíca, Suica, CH, SWI'},
 {'pais': 'Turquia',
  'descricao': 'Turquia é uma nação que possui 4 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 4 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=TR',
  'tags': 'Turquia, TR, TUR'},
 {'pais': 'Ucrânia',
  'descricao': 'Ucrânia é uma nação que possui 21 reatores nucleares, localizados em 5 cidades. Os reatores são dos tipos LWGR e PWR, sendo que, 4 Desativados Permanentemente, 15 em situação Operacional e 2 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=UA',
  'tags': 'Ucrânia, Ucrania, UA, UKR'},
 {'pais': 'Emirados Árabes Unidos',
  'descricao': 'Emirados Árabes Unidos é uma nação que possui 4 reatores nucleares, localizados em 1 cidade. Os reatores são do tipo PWR, sendo que, 4 em situação Operacional.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=AE',
  'tags': 'Emirados Árabes Unidos, Emirados Arabes Unidos, EAU, AE, UAE'},
 {'pais': 'Reino Unido',
  'descricao': 'Reino Unido é uma nação que possui 47 reatores nucleares, localizados em 22 cidades. Os reatores são dos tipos GCR, FBR, PWR e SGHWR, sendo que, 36 Desativados Permanentemente, 9 em situação Operacional e 2 Em Contrução.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=GB',
  'tags': 'Reino Unido, Inglaterra, GB, UKM'},
 {'pais': 'Estados Unidos',
  'descricao': 'Estados Unidos é uma nação que possui 135 reatores nucleares, localizados em 78 cidades. Os reatores são dos tipos PWR, BWR, PHWR, FBR, HTGR e não informado, sendo que, 94 em situação Operacional e 41 Desativados Permanentemente.',
  'fonte': 'https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=US',
  'tags': 'Estados Unidos, Estados Unidos da America, US, USA'}];
  
 let tipoReatores = [{'tipo': 'Reator de Água Pesada Pressurizada',
  'sigla': 'PHWR',
  'descricao': 'Um reator de água pesada pressurizada (PHWR) é um reator nuclear de potência que, comumente, utiliza urânio natural não enriquecido como seu combustível, que usa água pesada (deutério óxido D₂O) como seu refrigerante e moderador.'},
 {'tipo': 'Reator de Água Pressurizada',
  'sigla': 'PWR',
  'descricao': 'Reator de água leve moderado e resfriado por água pressurizada. Em um PWR, o núcleo do reator aquece água, que não ferve. Esta água quente então troca calor com um sistema de água de menor pressão, que se transforma em vapor e aciona a turbina.'},
 {'tipo': 'Reator de Água Fervente',
  'sigla': 'BWR',
  'descricao': 'Reator de água leve resfriado e moderado por água em ebulição. Em um BWR, o núcleo do reator aquece água, que se transforma em vapor e então aciona uma turbina a vapor.'},
 {'tipo': 'Reator Rápido Próxima Geração',
  'sigla': 'FBR',
  'descricao': 'Reatores de nêutrons rápidos usam nêutrons rápidos para causar fissão em seu combustível. Eles não têm um moderador de nêutrons, e usam menos moderadores de refrigerantes.'},
 {'tipo': 'Reator Resfriado a Gás',
  'sigla': 'GCR',
  'descricao': 'Um reator resfriado a gás é um reator nuclear que usa grafite como um moderador de nêutrons e dióxido de carbono (hélio também pode ser usado) como refrigerante.'},
 {'tipo': 'Reator de Água Leve Moderado por Grafite',
  'sigla': 'LWGR',
  'descricao': 'Reator de água leve resfriado por grafite moderado. Também conhecido como RBMK. Usando água leve para resfriamento e grafite para moderação, é possível usar urânio natural para combustível.'},
 {'tipo': 'Reator de Água Leve e Água Pesada',
  'sigla': 'HWLW',
  'descricao': 'Esse tipo de reator combina as características de reatores de água leve (como PWR e BWR) e de água pesada (como CANDU). Utiliza tanto água leve quanto água pesada como moderadores e refrigerantes. A ideia é aproveitar as vantagens de ambos os sistemas, como a alta eficiência da água pesada e a simplicidade da água leve.'},
 {'tipo': 'Reator Resfriado a Gás de Alta Temperatura',
  'sigla': 'HTGR',
  'descricao': 'Nestes reatores, o combustível nuclear está encapsulado em partículas de grafite, que são imersas em um gás inerte (geralmente hélio) a altas temperaturas. Essa configuração oferece uma alta segurança intrínseca, pois o combustível está fisicamente isolado e o refrigerante não entra em contato direto com ele.'},
 {'tipo': 'Reator Resfriado a Gás e Água Pesada',
  'sigla': 'HWGCR',
  'descricao': 'Essa sigla representa uma combinação de características de reatores resfriados a gás e reatores de água pesada. O combustível é moderado pela água pesada, mas o resfriamento é feito por um gás inerte.'},
 {'tipo': 'Reator de Água Pesada Gerador de Vapor',
  'sigla': 'SGHWR',
  'descricao': 'Neste tipo de reator, a água pesada serve tanto como moderador quanto como refrigerante. A água é aquecida no núcleo do reator e convertida em vapor, que por sua vez aciona uma turbina para gerar eletricidade.'}];